Updating redundant text
DTS-STN/Data-Patterns pull request #68
Opened 2021-08-30 19:03 UTC by Jordan-Morrison

2021-08-30 19:11 UTC, s-laugh requested changes
Not sure this actually fixes the issue...

ALSO, more importantly, all commits need to be signed and verified. So you will need to sign the commit you already made (basically creating a new commit that is signed).
https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification

2021-08-30 19:11 UTC, s-laugh commented on _patterns/opt-in.md
> +feature-img-alt: Privacy policy with with**checkbox prompt to agree and submit button.
The word "with" is still duplicated.

2021-08-31 15:42 UTC, Jordan-Morrison commented
Should be all good now!

2021-09-07 12:12 UTC, s-laugh approved these changes

2021-09-07 12:45 UTC, s-laugh commented
Looks like you'll need to sign your original commit as well for GitHub to accept the PR.
https://superuser.com/questions/397149/can-you-gpg-sign-old-commits

2021-09-08 17:54 UTC, closed without merging